import 'package:get/get.dart';

class BaseLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Good Morning ": 'Good Morning ',
          'Today': 'Today',
          'This Week': 'This Week',
          'This Month': 'This Month',
          "Start Time": 'Start Time',
          "End Time": 'End Time',
          "Save": 'Save',
          "Pull up load": 'Pull up load',
          "Load failed": 'Load failed',
          "Release to load more": 'Release to load more',
          "To-Do": 'To-Do',
          "Add Todo": 'Add Todo',
          "Terms & Conditions": 'Terms & Conditions',
          "Set Availability": 'Set Availability',
          "Service": 'Service',
          "Profile": 'Profile',
          "Professional Info": 'Professional Info',
          "Personal info": 'Personal info',
          "Experience Info": 'Experience Info',
          "Educational Info": 'Educational Info',
          "Notifications": 'Notifications',
          "Filter": 'Filter',
          "Sort By": 'Sort By',
          "Condition": 'Condition',
          "Category": 'Category',
          "+ Add New": '+ Add New',
          "Select Date": 'Select Date',
          "Update": 'Update',
          "Login": 'Login',
          "Continue": 'Continue',
          "sign Up": 'sign Up',
          "Update Availability": 'Update Availability',
          "Update Holiday": 'Update Holiday',
          "Add": 'Add',
          "Date of Issue": 'Date of Issue',
          "Date of Expiry": 'Date of Expiry',
          "Add Experience": 'Add Experience',
          "Select City": 'Select City',
          "Select Country": 'Select Country',
          "Select Gender": 'Select Gender',
          "Areas of Expertise": 'Areas of Expertise',
          "Graduation Year": 'Graduation Year',
          "Login with Google": 'Login with Google',
          "Login with Facebook": 'Login with Facebook',
          "Search": 'Search',
          "Email or Name": 'Email or Name',
          "Password": 'Password',
          "Medical School Attended": 'Medical School Attended',
          "Degree Obtained": 'Degree Obtained',
          "Additional Certifications": 'Additional Certifications',
          "First Name": 'First Name',
          "Last name": 'Last name',
          "Email": 'Email',
          "Date of birth": 'Date of birth',
          "Zip code": 'Zip code',
          "Phone Number": 'Phone Number',
          "Address": 'Address',
          "City": 'City',
          "Approbation (Medical License)": 'Approbation (Medical License)',
          "Upload License": 'Upload License',
          "Facharzt (Specialist)": 'Facharzt (Specialist)',
          "Select Category": 'Select Category',
          "Current Employer": 'Current Employer',
          "Previous Employers": 'Previous Employers',
          "Title First Name": 'Title First Name',
          "Confirm Password": 'Confirm Password',
          "Title": 'Title',
          "Date": 'Date',
          'Booked': 'Booked',
          "Slot Details": 'Slot Details',
          "View Slot": 'View Slot',
          "Complete": 'Complete',
          "Reschedule": 'Reschedule',
          "Cancel Appointment": 'Cancel Appointment',
          "Confirm": 'Confirm',
          "Description": 'Description',
          "Close": 'Close',
          "Previous 7 days": 'Previous 7 days',
          "Next 7 days": 'Next 7 days',
          "Appointments": 'Appointments',
          "No available slots": 'No available slots',
          'Upcoming': 'Upcoming',
          'Completed': 'Completed',
          'Canceled': 'Canceled',
          "Messages": 'Messages',
          "Open PDF": 'Open PDF',
          "My Appointment": 'My Appointment',
          "Daily Read": 'Daily Read',
          "DAILY READ": 'DAILY READ',
          "Visits for Today": 'Visits for Today',
          "Patient List": 'Patient List',
          "No Patients Found": 'No Patients Found',
          "View Slots": 'View Slots',
          "Calendar": 'Calendar',
          "Please wait while admin verify your profile.":
              'Please wait while admin verify your profile.',
          "You'll get email after approve to login the page":
              'You\'ll get email after approve to login the page',
          "Done": 'Done',
          "Appointment Rescheduled Successfully!":
              'Appointment Rescheduled Successfully!',
          "Your appointment has been successfully rescheduled. Here are the updated details:":
              'Your appointment has been successfully rescheduled. Here are the updated details:',
          "Keep me login": 'Keep me login',
          "Forgot Password?": 'Forgot Password?',
          "or login with": 'or login with',
          "Don’t have an account?": 'Don’t have an account?',
          "Create new account": 'Create new account',
          "New Booking": 'New Booking',
          "Clear All": 'Clear All',
          "No Data Found": 'No Data Found',
          "Patients": 'Patients',
          "Add Notes": 'Add Notes',
          "Appointment Details": 'Appointment Details',
          "Personal Information": 'Personal Information',
          "Gender": 'Gender',
          "Phone no": 'Phone no',
          "Country": 'Country',
          "Personal Info": 'Personal Info',
          "Edit": "Edit",
          "Select Categories": "Select Categories",
          'Doctor Registration': 'Doctor Registration',
          'If you already have an account,': 'If you already have an account,',
          "Login here": 'Login here',
          "I have read and accept 4Smile's ":
              'I have read and accept 4Smile\'s ',
          "Terms of Use": 'Terms of Use',
          "Privacy Policy": 'Privacy Policy',
          "Available Slots": 'Available Slots',
          "Day": "Day",
          "Slot": "Slot",
          "No Slots Available": "No Slots Available",
          "Status": "Status",
          "Available": "Available",
          "Holidays": "Holidays",
          "Holiday": "Holiday",
          "Set Holiday": "Set Holiday",
          "Select days": "Select days",
          "Start Date": "Start Date",
          "End Date": "End Date",
          "to": "to",
          "Date Parameters": "Date Parameters",
          "Every Week": "Every Week",
          "Specific Date Range": "Specific Date Range",
          "Availability": "Availability",
          "Camera": "Camera",
          "Gallery": "Gallery",
          "Cancel": "Cancel",
          "Select Time": "Select Time",
          "No Connection!": "No Connection!",
          "No Data Found!": "No Data Found!",
          "No chat available": "No chat available",
          "We encountered an error and we've notified our engineering team about it. Sorry for the inconvenience caused.":
              "We encountered an error and we've notified our engineering team about it. Sorry for the inconvenience caused.",
          "Good Afternoon": "Good Afternoon",
          "Good Evening": "Good Evening",
          "Good Night": "Good Night",
          "New Patients": "New Patients",
          "Old Patients": "Old Patients",
          "Dashboard": "Dashboard",
          "To-Do ": "To-Do ",
          "Log Out": "Log Out",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday": "Saturday",
          "Sunday": "Sunday",
          "Patient Form": "Patient Form",

          //////
          'Fill Form': 'Fill Form',
          "Book Now": "Book Now",
          "Verify": "Verify",
          "Select Condition": "Select Condition",
          "OTP": "OTP",
          "Confirmed": "Confirmed",
          "Book Your Appointment": "Book Your Appointment",
          "Past Appointment": "Past Appointment",
          "Doctors": "Doctors",
          "Read More": "Read More",
          "Select Date And Time": "Select Date And Time",
          "Book Other Doctor": "Book Other Doctor",
          'Kindly enter your password to confirm':
              'Kindly enter your password to confirm',
          'An OTP has been sent your email': 'An OTP has been sent your email',
          'Did not recieve code? 00:30s': 'Did not recieve code? 00:30s',
          "Resend OTP": "Resend OTP",
          "Patient Registration": "Patient Registration",
          "No Appointment Found": "No Appointment Found",
          "No Past Appointment Found": "No Past Appointment Found",
          "Doctor": "Doctor",
          "Appointments History": "Appointments History",
        },
        ////////////
        //////////
        //////////
        //////////
        //////
        'de_DE': {
          "Good Morning ": "Guten Morgen ",
          "Today": "Heute",
          "This Week": "Diese Woche",
          "This Month": "Diesen Monat",
          "Start Time": "Startzeit",
          "End Time": "Endzeit",
          "Save": "Speichern",
          "Pull up load": "Zum Laden nach oben ziehen",
          "Load failed": "Laden fehlgeschlagen",
          "Release to load more": "Loslassen zum Laden",
          "To-Do": "Aufgabe",
          "Add Todo": "Aufgabe hinzufügen",
          "Terms & Conditions": "Allgemeine Geschäftsbedingungen",
          "Set Availability": "Verfügbarkeit festlegen",
          "Service": "Dienstleistung",
          "Profile": "Profil",
          "Professional Info": "Berufliche Informationen",
          "Personal info": "Persönliche Informationen",
          "Experience Info": "Erfahrungsinformationen",
          "Educational Info": "Ausbildungsinformationen",
          "Notifications": "Benachrichtigungen",
          "Filter": "Filter",
          "Sort By": "Sortieren nach",
          "Condition": "Zustand",
          "Category": "Kategorie",
          "+ Add New": "+ Neu hinzufügen",
          "Select Date": "Datum auswählen",
          "Update": "Aktualisieren",
          "Login": "Anmelden",
          "Continue": "Fortfahren",
          "sign Up": "Registrieren",
          "Update Availability": "Verfügbarkeit aktualisieren",
          "Update Holiday": "Urlaub aktualisieren",
          "Add": "Hinzufügen",
          "Date of Issue": "Ausgabedatum",
          "Date of Expiry": "Ablaufdatum",
          "Add Experience": "Erfahrung hinzufügen",
          "Select City": "Stadt auswählen",
          "Select Country": "Land auswählen",
          "Select Gender": "Geschlecht auswählen",
          "Areas of Expertise": "Fachgebiete",
          "Graduation Year": "Abschlussjahr",
          "Login with Google": "Mit Google anmelden",
          "Login with Facebook": "Mit Facebook anmelden",
          "Search": "Suchen",
          "Email or Name": "E-Mail oder Name",
          "Password": "Passwort",
          "Medical School Attended": "Besuchte medizinische Schule",
          "Degree Obtained": "Abschluss erhalten",
          "Additional Certifications": "Zusätzliche Zertifikate",
          "First Name": "Vorname",
          "Last name": "Nachname",
          "Email": "E-Mail",
          "Date of birth": "Geburtsdatum",
          "Zip code": "Postleitzahl",
          "Phone Number": "Telefonnummer",
          "Address": "Adresse",
          "City": "Stadt",
          "Approbation (Medical License)": "Approbation (ärztliche Zulassung)",
          "Upload License": "Lizenz hochladen",
          "Facharzt (Specialist)": "Facharzt",
          "Select Category": "Kategorie auswählen",
          "Current Employer": "Aktueller Arbeitgeber",
          "Previous Employers": "Frühere Arbeitgeber",
          "Title First Name": "Titel Vorname",
          "Confirm Password": "Passwort bestätigen",
          "Title": "Titel",
          "Date": "Datum",
          "Booked": "Gebucht",
          "Slot Details": "Slot-Details",
          "View Slot": "Slot anzeigen",
          "Complete": "Abschließen",
          "Reschedule": "Neu planen",
          "Cancel Appointment": "Termin absagen",
          "Confirm": "Bestätigen",
          "Description": "Beschreibung",
          "Close": "Schließen",
          "Previous 7 days": "Letzte 7 Tage",
          "Next 7 days": "Nächste 7 Tage",
          "Appointments": "Termine",
          "No available slots": "Keine verfügbaren Slots",
          "Upcoming": "Bevorstehend",
          "Completed": "Abgeschlossen",
          "Canceled": "Abgesagt",
          "Messages": "Nachrichten",
          "Open PDF": "PDF öffnen",
          "My Appointment": "Mein Termin",
          "Daily Read": "Tägliche Lektüre",
          "DAILY READ": "TÄGLICHE LEKTÜRE",
          "Visits for Today": "Besuche heute",
          "Patient List": "Patientenliste",
          "No Patients Found": "Keine Patienten gefunden",
          "View Slots": "Slots anzeigen",
          "Calendar": "Kalender",
          "Please wait while admin verify your profile.":
              "Bitte warten Sie, während der Administrator Ihr Profil überprüft.",
          "You'll get email after approve to login the page":
              "Sie erhalten eine E-Mail, sobald Ihr Zugang genehmigt wurde.",
          "Done": "Fertig",
          "Appointment Rescheduled Successfully!":
              "Termin erfolgreich neu geplant!",
          "Your appointment has been successfully rescheduled. Here are the updated details:":
              "Ihr Termin wurde erfolgreich neu geplant. Hier sind die aktualisierten Details:",
          "Keep me login": "Angemeldet bleiben",
          "Forgot Password?": "Passwort vergessen?",
          "or login with": "oder anmelden mit",
          "Don’t have an account?": "Noch kein Konto?",
          "Create new account": "Neues Konto erstellen",
          "New Booking": "Neue Buchung",
          "Clear All": "Alles löschen",
          "No Data Found": "Keine Daten gefunden",
          "Patients": "Patienten",
          "Add Notes": "Notizen hinzufügen",
          "Appointment Details": "Termindetails",
          "Personal Information": "Persönliche Informationen",
          "Gender": "Geschlecht",
          "Phone no": "Telefonnummer",
          "Country": "Land",
          "Personal Info": "Persönliche Informationen",
          "Edit": "Bearbeiten",
          "Select Categories": "Kategorien auswählen",
          "Doctor Registration": "Arztregistrierung",
          "If you already have an account,":
              "Wenn Sie bereits ein Konto haben,",
          "Login here": "Hier anmelden",
          "I have read and accept 4Smile's ": "Ich habe die 4Smile ",
          "Terms of Use": "Nutzungsbedingungen",
          "Privacy Policy": "Datenschutzrichtlinie",
          "Available Slots": "Verfügbare Slots",
          "Day": "Tag",
          "Slot": "Slot",
          "No Slots Available": "Keine Slots verfügbar",
          "Status": "Status",
          "Available": "Verfügbar",
          "Holidays": "Feiertage",
          "Holiday": "Feiertag",
          "Set Holiday": "Feiertag festlegen",
          "Select days": "Tage auswählen",
          "Start Date": "Startdatum",
          "End Date": "Enddatum",
          "to": "bis",
          "Date Parameters": "Datumsparameter",
          "Every Week": "Jede Woche",
          "Specific Date Range": "Bestimmter Datumsbereich",
          "Availability": "Verfügbarkeit",
          "Camera": "Kamera",
          "Gallery": "Galerie",
          "Cancel": "Abbrechen",
          "Select Time": "Uhrzeit auswählen",
          "No Connection!": "Keine Verbindung!",
          "No Data Found!": "Keine Daten gefunden!",
          "No chat available": "Kein Chat verfügbar",
          "We encountered an error and we've notified our engineering team about it. Sorry for the inconvenience caused.":
              "Es ist ein Fehler aufgetreten. Unser Technikteam wurde benachrichtigt. Entschuldigung für die Unannehmlichkeiten.",
          "Good Afternoon": "Guten Tag",
          "Good Evening": "Guten Abend",
          "Good Night": "Gute Nacht",
          "New Patients": "Neuer Patient",
          "Old Patients": "Alter Patient",
          "Dashboard": "Dashboard",
          "To-Do ": "To-Do",
          "Log Out": "Abmelden",
          "Monday": "Montag",
          "Tuesday": "Dienstag",
          "Wednesday": "Mittwoch",
          "Thursday": "Donnerstag",
          "Friday": "Freitag",
          "Saturday": "Samstag",
          "Sunday": "Sonntag",
          "Patient Form": "Patientenformular",
          /////
          "Fill Form": "Formular ausfüllen",
          "Book Now": "Jetzt buchen",
          "Verify": "Bestätigen",
          "Select Condition": "Bedingung auswählen",
          "OTP": "Einmalpasswort",
          "Confirmed": "Bestätigt",
          "Book Your Appointment": "Termin buchen",
          "Past Appointment": "Vergangener Termin",
          "Doctors": "Ärzte",
          "Read More": "Mehr erfahren",
          "Select Date And Time": "Datum und Uhrzeit auswählen",
          "Book Other Doctor": "Anderen Arzt buchen",
          "Kindly enter your password to confirm":
              "Bitte geben Sie Ihr Passwort zur Bestätigung ein",
          "An OTP has been sent your email":
              "Ein Einmalpasswort wurde an Ihre E-Mail gesendet",
          "Did not recieve code? 00:30s": "Code nicht erhalten? 00:30s",
          "Resend OTP": "Einmalpasswort erneut senden",
          "Patient Registration": "Patientenanmeldung",
          "No Appointment Found": "Kein Termin gefunden",
          "No Past Appointment Found": "Kein vergangener Termin gefunden",
          "Doctor": "Arzt",
          "Appointments History": "Terminhistorie"
        }
      };
}
